(add-to-list 'load-path "~/.emacs.d/extensions/auto-complete/")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/extensions/auto-complete/ac-dict")
(ac-config-default)
(setq ac-delay 0.1)
;;(ac-fuzzy-complete)
